"""
SFT (Supervised Fine-Tuning) training script for GSM8K.

Trains Qwen2-0.5B-Instruct on gold standard dataset generated by Claude.
Uses HuggingFace Trainer API with early stopping.

Usage:
    python sft_train.py --num_examples 500 --output_dir output/sft-500
    python sft_train.py --num_examples 250 --output_dir output/sft-250
    python sft_train.py --num_examples 100 --output_dir output/sft-100
"""

import os
import json
import argparse
import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback
)

# ── System prompt (same as GRPO training) ─────────────────────────────────────
SYSTEM_PROMPT = """You must reply in exactly the following XML format and nothing else:

<reasoning>
...your reasoning...
</reasoning>
<answer>
INTEGER
</answer>

Rules:
- The very first characters of your response must be "<reasoning>\\n".
- Place only a single integer inside <answer> tags.
- Do not include any text before <reasoning> or after </answer>."""


def load_sft_dataset(filepath, num_examples, tokenizer, max_length=1024):
    """Load and tokenize SFT dataset."""
    
    with open(filepath) as f:
        data = json.load(f)
    
    # Take first num_examples
    data = data[:num_examples]
    print(f"Loaded {len(data)} examples")
    
    def format_example(item):
        """Format question + solution as a full chat conversation."""
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": item["question"]},
            {"role": "assistant", "content": item["solution"]}
        ]
        
        # Apply chat template
        full_text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False
        )
        return full_text
    
    def tokenize(example):
        full_text = format_example(example)
        
        # Tokenize full conversation
        tokenized = tokenizer(
            full_text,
            truncation=True,
            max_length=max_length,
            padding=False,
            return_tensors=None
        )
        
        # Create labels — mask everything except assistant response
        # Find where assistant response starts
        prompt_messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": example["question"]}
        ]
        prompt_text = tokenizer.apply_chat_template(
            prompt_messages,
            tokenize=False,
            add_generation_prompt=True
        )
        prompt_tokens = tokenizer(
            prompt_text,
            truncation=True,
            max_length=max_length,
            padding=False,
            return_tensors=None
        )
        
        prompt_length = len(prompt_tokens["input_ids"])
        
        # Labels: -100 for prompt tokens (ignored in loss), actual ids for response
        labels = [-100] * prompt_length + tokenized["input_ids"][prompt_length:]
        tokenized["labels"] = labels
        
        return tokenized
    
    # Create HuggingFace dataset
    hf_dataset = Dataset.from_list(data)
    tokenized_dataset = hf_dataset.map(tokenize, remove_columns=hf_dataset.column_names)
    
    return tokenized_dataset


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", type=str, default="Qwen/Qwen2-0.5B-Instruct")
    parser.add_argument("--dataset_file", type=str, default="sft_dataset.json")
    parser.add_argument("--num_examples", type=int, default=500)
    parser.add_argument("--output_dir", type=str, default="output/sft-500")
    parser.add_argument("--max_length", type=int, default=1024)
    parser.add_argument("--learning_rate", type=float, default=2e-5)
    parser.add_argument("--max_epochs", type=int, default=10)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=4)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")
    print(f"Training on {args.num_examples} examples")
    print(f"Output dir: {args.output_dir}")

    # ── Load model and tokenizer ───────────────────────────────────────────────
    print(f"\nLoading {args.model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_name)
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.model_name,
        torch_dtype=torch.bfloat16,
        attn_implementation="eager",
        device_map=None
    ).to(device)
    model.config.use_cache = False

    # ── Load dataset ───────────────────────────────────────────────────────────
    print("\nLoading and tokenizing dataset...")
    full_dataset = load_sft_dataset(
        args.dataset_file,
        args.num_examples,
        tokenizer,
        args.max_length
    )

    # 90/10 train/val split for early stopping
    split = full_dataset.train_test_split(test_size=0.1, seed=args.seed)
    train_dataset = split["train"]
    val_dataset = split["test"]

    print(f"Train: {len(train_dataset)} examples")
    print(f"Val:   {len(val_dataset)} examples")

    # ── Training arguments ─────────────────────────────────────────────────────
    os.makedirs(args.output_dir, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.max_epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        warmup_ratio=args.warmup_ratio,
        bf16=True,
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        seed=args.seed,
        report_to="none",
        dataloader_pin_memory=False,
    )

    # ── Data collator ──────────────────────────────────────────────────────────
    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        model=model,
        padding=True,
        pad_to_multiple_of=8
    )

    # ── Trainer ────────────────────────────────────────────────────────────────
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
    )

    # ── Train ──────────────────────────────────────────────────────────────────
    print("\nStarting SFT training...")
    trainer.train()

    # ── Save final model ───────────────────────────────────────────────────────
    final_dir = os.path.join(args.output_dir, "final")
    model.save_pretrained(final_dir)
    tokenizer.save_pretrained(final_dir)
    print(f"\nSaved final model to {final_dir}")


if __name__ == "__main__":
    main()